dist: trusty
language: rust
rust:
- nightly
- stable
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    - cmake
script:
- export CC=/usr/bin/gcc-8
- export CXX=/usr/bin/g++-8
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo build --no-default-features;
  fi
- cargo build --release --verbose
- cargo test --release --verbose
- cargo test --release --manifest-path=spec/Cargo.toml
- cargo run --example bench-decoder --release
after_success: |-
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc \
  && echo '<meta http-equiv=refresh content=0;url=parity_wasm/index.html>' > target/doc/index.html && \
  sudo pip install ghp-import && \
  ghp-import -n target/doc && \
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - RUSTFLAGS=--cfg=slow_assertions
  - CC=/usr/bin/gcc-8
  - CXX=/usr/bin/g++-8
  - secure: kHPUuykUjlSOMk6ArSIto+mgyBR34lNcEpP7uk+BTg9U/EtZ+kjdqEbrsSyJRUcUTQf7Da8H+2m02o6h3CuBVkZRIwGfwrZ9y8aHOePH/vIYbZ8Syb/J/2PHbGkVbV1DeF0aXIA4VdRU6opfetre6Bh3/hfkLfEFlu8wvC5wVg1ezsRzFVVGfr3qgY3b33SaZw7cHw1B+bcM+mJd4FeXbhJn3V7b2pSnxk9d8QHK4izccYV7rPSrYiOd64NciO53g+3Tc9O0PSq/vojIPR1jQ+ku2/91cWTUzAQ4LOkV0ekR50y6CDxj+LYRUI3E8XnLhRje+ErBhI1K3TbaxDSuzxj+zcVVS1Miio9X/yq9tJqmYmeMt9OvGNOT4fTv2cd+O1ZrFy/MJL/VnV9S6paxeeb742DZ/AkL02q6o34xv6kXrj5UBoLEyTRgYQi2tzrCLA3xf0678e/9NIRt6tIe0PwiCF54kNsXE67gsicCmKAhv1V/YKhN9WqyNpSDUlX78fDFbiqY8yGAkNu5OdwcfoifadoP5jHVwSSLFotLy4mYvvH5VtwJHPakY3eQYncuieUdbPiH0PO74XudptLuPWzLzvfcsNy35uqSeSlrGIM52Pan/QRntZvnuX67cyn6uYti3AMpcaDJL3gQ+YfP1MXYlJTN9w4pFmpqPXz2+7A=
