language: rust
script:
    - cargo build --release --verbose
    - cargo test --release --verbose
    - cargo test --release --manifest-path=spec/Cargo.toml 
after_success: |
    cargo doc \
    && echo '<meta http-equiv=refresh content=0;url=parity_wasm/index.html>' > target/doc/index.html && \
    sudo pip install ghp-import && \
    ghp-import -n target/doc && \
    git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages