[package]
name = "parity-wasm"
version = "0.3.2"
authors = ["NikVolf <nikvolf@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/nikvolf/parity-wasm"
homepage = "https://github.com/nikvolf/parity-wasm"
documentation = "https://nikvolf.github.io/parity-wasm/parity_wasm/"
description = "WebAssembly binary format serialization/deserialization"
keywords = ["wasm", "webassembly", "bytecode", "serde"] 
exclude = [ "res/*" ]

[dependencies]
byteorder = "1.0"
